project_id = "promptdevkit-web"
project_ref = "promptdevkit-web"
organization_id = "local"

[db]
major_version = 15
port = 54322
shadow_port = 54320

[studio]
port = 54323

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["extensions"]
max_rows = 1000

[inbucket]
port = 54324

[storage]
file_size_limit = 52428800

[edge_runtime]
port = 54325
